# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/krysak/Documents/WebScope-0.1.0/src/Application/UiFiles/SourcePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sourcePage(object):
    def setupUi(self, sourcePage):
        sourcePage.setObjectName("sourcePage")
        sourcePage.resize(1049, 580)
        self.mainLayout = QtWidgets.QVBoxLayout(sourcePage)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.sa_source_code = QtWidgets.QScrollArea(sourcePage)
        self.sa_source_code.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sa_source_code.setWidgetResizable(True)
        self.sa_source_code.setObjectName("sa_source_code")
        self.sourceCodeScrollContent = QtWidgets.QWidget()
        self.sourceCodeScrollContent.setGeometry(QtCore.QRect(0, 0, 1049, 580))
        self.sourceCodeScrollContent.setObjectName("sourceCodeScrollContent")
        self.sourceCodeScrollLayout = QtWidgets.QVBoxLayout(self.sourceCodeScrollContent)
        self.sourceCodeScrollLayout.setContentsMargins(15, 15, 15, 15)
        self.sourceCodeScrollLayout.setSpacing(20)
        self.sourceCodeScrollLayout.setObjectName("sourceCodeScrollLayout")
        self.te_preview = QtWidgets.QTextEdit(self.sourceCodeScrollContent)
        self.te_preview.setMinimumSize(QtCore.QSize(0, 250))
        self.te_preview.setReadOnly(True)
        self.te_preview.setObjectName("te_preview")
        self.sourceCodeScrollLayout.addWidget(self.te_preview)
        self.grid_styling = QtWidgets.QGridLayout()
        self.grid_styling.setObjectName("grid_styling")
        self.btn_sel_tags = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_sel_tags.setCheckable(True)
        self.btn_sel_tags.setObjectName("btn_sel_tags")
        self.btn_group = QtWidgets.QButtonGroup(sourcePage)
        self.btn_group.setObjectName("btn_group")
        self.btn_group.addButton(self.btn_sel_tags)
        self.grid_styling.addWidget(self.btn_sel_tags, 0, 0, 1, 1)
        self.btn_sel_attrs = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_sel_attrs.setCheckable(True)
        self.btn_sel_attrs.setObjectName("btn_sel_attrs")
        self.btn_group.addButton(self.btn_sel_attrs)
        self.grid_styling.addWidget(self.btn_sel_attrs, 0, 1, 1, 1)
        self.btn_sel_strings = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_sel_strings.setCheckable(True)
        self.btn_sel_strings.setObjectName("btn_sel_strings")
        self.btn_group.addButton(self.btn_sel_strings)
        self.grid_styling.addWidget(self.btn_sel_strings, 1, 0, 1, 1)
        self.btn_sel_comments = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_sel_comments.setCheckable(True)
        self.btn_sel_comments.setObjectName("btn_sel_comments")
        self.btn_group.addButton(self.btn_sel_comments)
        self.grid_styling.addWidget(self.btn_sel_comments, 1, 1, 1, 1)
        self.sourceCodeScrollLayout.addLayout(self.grid_styling)
        self.style_tools = QtWidgets.QHBoxLayout()
        self.style_tools.setObjectName("style_tools")
        self.btn_style_color = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_style_color.setObjectName("btn_style_color")
        self.style_tools.addWidget(self.btn_style_color)
        self.btn_style_bold = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_style_bold.setCheckable(True)
        self.btn_style_bold.setObjectName("btn_style_bold")
        self.style_tools.addWidget(self.btn_style_bold)
        self.btn_style_italic = QtWidgets.QPushButton(self.sourceCodeScrollContent)
        self.btn_style_italic.setCheckable(True)
        self.btn_style_italic.setObjectName("btn_style_italic")
        self.style_tools.addWidget(self.btn_style_italic)
        self.sourceCodeScrollLayout.addLayout(self.style_tools)
        self.layout_features = QtWidgets.QVBoxLayout()
        self.layout_features.setSpacing(8)
        self.layout_features.setObjectName("layout_features")
        self.chk_auto_close = QtWidgets.QCheckBox(self.sourceCodeScrollContent)
        self.chk_auto_close.setObjectName("chk_auto_close")
        self.layout_features.addWidget(self.chk_auto_close)
        self.chk_line_numbers = QtWidgets.QCheckBox(self.sourceCodeScrollContent)
        self.chk_line_numbers.setObjectName("chk_line_numbers")
        self.layout_features.addWidget(self.chk_line_numbers)
        self.chk_word_wrap = QtWidgets.QCheckBox(self.sourceCodeScrollContent)
        self.chk_word_wrap.setObjectName("chk_word_wrap")
        self.layout_features.addWidget(self.chk_word_wrap)
        self.chk_format_save = QtWidgets.QCheckBox(self.sourceCodeScrollContent)
        self.chk_format_save.setObjectName("chk_format_save")
        self.layout_features.addWidget(self.chk_format_save)
        self.sourceCodeScrollLayout.addLayout(self.layout_features)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sourceCodeScrollLayout.addItem(spacerItem)
        self.sa_source_code.setWidget(self.sourceCodeScrollContent)
        self.mainLayout.addWidget(self.sa_source_code)

        self.retranslateUi(sourcePage)
        QtCore.QMetaObject.connectSlotsByName(sourcePage)

    def retranslateUi(self, sourcePage):
        _translate = QtCore.QCoreApplication.translate
        self.te_preview.setHtml(_translate("sourcePage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<pre style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#808080;\">&lt;!-- HTML --&gt;</span></pre>\n"
"<pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#569cd6;\">&lt;div</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\"> </span><span style=\" font-family:\'monospace\'; color:#9cdcfe;\">class</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\">=</span><span style=\" font-family:\'monospace\'; color:#ce9178;\">&quot;box&quot;</span><span style=\" font-family:\'monospace\'; color:#569cd6;\">&gt;</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\">Xyra</span><span style=\" font-family:\'monospace\'; color:#569cd6;\">&lt;/div&gt;</span></pre>\n"
"<pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; color:#569cd6; background-color:#1e1e1e;\"><br /></pre>\n"
"<pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#808080;\">/* CSS */</span></pre>\n"
"<pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#d7ba7d;\">.box</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\"> { </span><span style=\" font-family:\'monospace\'; color:#9cdcfe;\">display</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\">: flex; }</span></pre>\n"
"<pre style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; color:#d4d4d4; background-color:#1e1e1e;\"><br /></pre>\n"
"<pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#808080;\">// JS</span></pre>\n"
"<pre style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#1e1e1e;\"><span style=\" font-family:\'monospace\'; color:#569cd6;\">const</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\"> </span><span style=\" font-family:\'monospace\'; color:#9cdcfe;\">init</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\"> = () =&gt; </span><span style=\" font-family:\'monospace\'; color:#b5cea8;\">true</span><span style=\" font-family:\'monospace\'; color:#d4d4d4;\">;</span></pre></body></html>"))
        self.btn_sel_tags.setText(_translate("sourcePage", "HTML Tags"))
        self.btn_sel_attrs.setText(_translate("sourcePage", "Attributes"))
        self.btn_sel_strings.setText(_translate("sourcePage", "Strings"))
        self.btn_sel_comments.setText(_translate("sourcePage", "Comments"))
        self.btn_style_color.setText(_translate("sourcePage", "Color"))
        self.btn_style_bold.setText(_translate("sourcePage", "B"))
        self.btn_style_italic.setText(_translate("sourcePage", "I"))
        self.chk_auto_close.setText(_translate("sourcePage", "Auto-close Tags & Brackets"))
        self.chk_line_numbers.setText(_translate("sourcePage", "Show Line Numbers"))
        self.chk_word_wrap.setText(_translate("sourcePage", "Enable Word Wrap"))
        self.chk_format_save.setText(_translate("sourcePage", "Format on Save"))
